### ISSUE TITLE
Make runnable jar

### ISSUE THREAD

**Issue by jamierocks** [NeptunePowered/NeptuneVanilla#1]

**Comment by jamierocks** [comment]
Fixed in https://github.com/NeptunePowered/NeptuneVanilla/commit/a95633fa98104a1a42782e2180b752fb1599488d.

**Comment by 14mRh4X0r** [comment]
Doesn't work when the jar is symlinked:

```
Exception in thread "main" java.lang.NoClassDefFoundError: net/minecraft/launchwrapper/Launch
    at org.neptunepowered.vanilla.launch.server.NeptuneServerMain.main(NeptuneServerMain.java:61)
Caused by: java.lang.ClassNotFoundException: net.minecraft.launchwrapper.Launch
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 1 more
```

**Comment by jamierocks** [comment]
What command did you use to build?

**Comment by 14mRh4X0r** [comment]
`./gradlew build`

**Comment by jamierocks** [comment]
Is Java behind a firewall, etc?
Does lib/launchwrapper-1.11.jar exist?

**Comment by 14mRh4X0r** [comment]
I think this is actually an issue with Java where it tries to resolve the class path relative to the hard location of the jar, when I don't symlink the Neptune jar it works fine.

**Comment by jamierocks** [comment]
Ah, thats a pain. :S
